// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/fulltask": {
            "post": {
                "description": "Uploads a file and processes it for a full task",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "plain/text"
                ],
                "summary": "Upload a file for a full task",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File uploaded successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error retrieving the file",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error opening or reading the file",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/shorttask": {
            "post": {
                "description": "Uploads a file and processes it for a short task",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "plain/text"
                ],
                "summary": "Upload a file for a short task",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File uploaded successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error retrieving the file",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error opening or reading the file",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
