definitions:
  messages.MessageResult:
    properties:
      messageText:
        type: string
      result:
        type: integer
      submitDate:
        type: string
      userID:
        type: string
    type: object
  structs.FileTaskResponse:
    properties:
      id:
        type: string
      messages:
        items:
          $ref: '#/definitions/messages.MessageResult'
        type: array
      type:
        type: string
    type: object
  structs.TextTaskRequest:
    properties:
      text:
        type: string
    type: object
  structs.TextTaskResponse:
    properties:
      result:
        type: integer
      text:
        type: string
    type: object
info:
  contact: {}
paths:
  /binary/full/:
    post:
      consumes:
      - multipart/form-data
      description: Uploads a file and processes it for a task
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - plain/text
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/structs.FileTaskResponse'
        "400":
          description: Error retrieving the file
          schema:
            type: string
        "500":
          description: Error opening or reading the file
          schema:
            type: string
      summary: Upload a file for a full task
  /binary/short:
    post:
      consumes:
      - application/json
      description: Uploads a text and processes it for a task
      parameters:
      - description: Text for a task
        in: body
        name: text
        required: true
        schema:
          $ref: '#/definitions/structs.TextTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/structs.TextTaskResponse'
        "400":
          description: Error retrieving the file
          schema:
            type: string
        "500":
          description: Error opening or reading the file
          schema:
            type: string
      summary: Upload a text for a short task
swagger: "2.0"
